import type { ImportMap } from "payload";

// This file is normally regenerated by `payload generate:importmap` whenever
// custom admin components are registered in payload.config.ts. This project
// does not currently register any custom components, so the map is empty.
export const importMap: ImportMap = {};
