import type { Metadata } from "next";
import "./globals.css";

// NOTE: Font loading (Playfair Display, Inter, Noto Serif Ethiopic) is wired
// up in Chunk 2 via <link> tags in the <head>, matching index.html's
// approach exactly (rather than next/font/google, which self-hosts fonts
// downloaded at build time).

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full antialiased">
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}